In [1]:
import pandas as pd
import matplotlib.pyplot as plt

Recom_data = pd.read_csv("D:\\Datasets\\Recommendation_Data.csv")
Recom_data.head(10)

,CUSTOMER_ID,RECOMMENDATION_NAME,RECOMMENDATION_DATE,SUGGESTION_TYPE,PURCHASE_FLAG
0,1.0,Recommend_Screenguard,7/2/2025,With Cover,0.0
1,2.0,Recommend_Screenguard,7/3/2025,With Phone,0.0
2,3.0,Recommend_Screenguard,7/4/2025,With Phone,0.0
3,4.0,Recommend_Screenguard,7/5/2025,With Cover,1.0
4,5.0,Recommend_Screenguard,7/6/2025,With Cover,1.0
5,6.0,Recommend_Screenguard,7/7/2025,With Phone,0.0
6,7.0,Recommend_Screenguard,7/8/2025,With Phone,1.0
7,8.0,Recommend_Screenguard,7/9/2025,With Phone,0.0
8,9.0,Recommend_Screenguard,7/10/2025,With Cover,0.0
9,10.0,Recommend_Screenguard,7/11/2025,With Phone,0.0

In [2]:
Recom_data.dropna(inplace=True)
Recom_data["CUSTOMER_ID"] = Recom_data["CUSTOMER_ID"].astype("int64")
Recom_data["PURCHASE_FLAG"] = Recom_data["PURCHASE_FLAG"].astype("int64")
Recom_data.head(10)

,CUSTOMER_ID,RECOMMENDATION_NAME,RECOMMENDATION_DATE,SUGGESTION_TYPE,PURCHASE_FLAG
0,1,Recommend_Screenguard,7/2/2025,With Cover,0
1,2,Recommend_Screenguard,7/3/2025,With Phone,0
2,3,Recommend_Screenguard,7/4/2025,With Phone,0
3,4,Recommend_Screenguard,7/5/2025,With Cover,1
4,5,Recommend_Screenguard,7/6/2025,With Cover,1
5,6,Recommend_Screenguard,7/7/2025,With Phone,0
6,7,Recommend_Screenguard,7/8/2025,With Phone,1
7,8,Recommend_Screenguard,7/9/2025,With Phone,0
8,9,Recommend_Screenguard,7/10/2025,With Cover,0
9,10,Recommend_Screenguard,7/11/2025,With Phone,0

In [3]:

type(Recom_data)

pandas.DataFrame

In [4]:
Recom_data.shape

(713, 5)

In [5]:
Recom_data.groupby("SUGGESTION_TYPE")["PURCHASE_FLAG"].value_counts()

SUGGESTION_TYPE  PURCHASE_FLAG
With Cover       1                195
                 0                165
With Phone       0                200
                 1                153
Name: count, dtype: int64

In [6]:
#Recom_data[Recom_data["SUGGESTION_TYPE"].str.contains(r"[\r\n]", na=False)]

Empty DataFrame
Columns: [CUSTOMER_ID, RECOMMENDATION_NAME, RECOMMENDATION_DATE, SUGGESTION_TYPE, PURCHASE_FLAG]
Index: []

In [27]:
#Recom_data["SUGGESTION_TYPE"]=Recom_data["SUGGESTION_TYPE"].str.strip()
#Recom_data["SUGGESTION_TYPE"]=Recom_data["SUGGESTION_TYPE"].replace("", pd.NA)

# These syntaxes for removing \r\n in the old dataset

In [8]:
Recom_data.groupby("SUGGESTION_TYPE")["PURCHASE_FLAG"].value_counts()

SUGGESTION_TYPE  PURCHASE_FLAG
With Cover       1                195
                 0                165
With Phone       0                200
                 1                153
Name: count, dtype: int64

In [9]:
# WHAT IS THE COUNT OF PURCHASED AND NOT PURCHASED IN "WITH COVER" CATREGORY & 
# WHAT IS THE COUNT OF PURCHASED AND NOT PURCHASED IN "WITH PHONE" CATREGORY - FORMS CONTINGENCY TABLE 
# THIS IS WHAT WE ARE FINDING USING CROSSTAB

CT_Values = pd.crosstab(Recom_data ["SUGGESTION_TYPE"], Recom_data["PURCHASE_FLAG"]).values
CT_Values

array([[165, 195],
       [200, 153]])

In [11]:
#COMPUTE PURCHASE RATE
With_Phone_Rate = 153 / (153+200)
With_Cover_Rate = 195 / (195+165)
print("Phone With ScreenGuard", With_Phone_Rate)
print("Cover With ScreenGuard", With_Cover_Rate)

Phone With ScreenGuard 0.43342776203966005
Cover With ScreenGuard 0.5416666666666666

NULL HYPOTHESIS = "THERE IS NO RELATIONSHIP B/W PURCHASE RATE & RECOMMENDATION TYPE. THEY ARE INDEPENDENT"
ALTERNATE HYPOTHESIS = " THERE IS RELATIONSHIP B/W PURCHASE RATE & RECOMMENDATION TYPE. THEY ARE NOT INDEPENDENT"

In [13]:
from scipy.stats import chi2_contingency
chi2_statistic, p_value, dof, expected_values = chi2_contingency(CT_Values, correction = False)
print(chi2_statistic, p_value)

8.357211722028106 0.0038415958864807726

In [14]:
prob = 0.95
alpha = 1.0 - prob
print('significant=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('Dependent, we can reject H0 safely')
else:
    print('Independent, No Sufficient Evidence to Reject H0')

significant=0.050, p=0.004
Dependent, we can reject H0 safely